#!/bin/bash

set -e

# Add a new user
if ! id "dashboard" &>/dev/null; then
    useradd -m -s /bin/bash dashboard
    echo "User dashboard created."
else
    echo "User dashboard already exists."
fi

# Ensure the startup script is executable
chmod +x /usr/share/dashboard/start.sh

# Install bun.js
curl -fsSL https://bun.sh/install | BUN_INSTALL="/tmp" bash
mv /tmp/bin/bun /usr/local/bin/bun

exit 0