name: Nextjs Docker Publish

on:
  push:
    tags:
      - "v*.*.*" # run on semver tags
      - "v*.*.*-*" # run on pre-release tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: iconcommunity/relayer-admin-dashboard:latest