name: Build, package and release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and release'
        required: true
      is_stable:
        description: 'Is this a stable release?'
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Next.js application
        run: bun run build

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Update control file version
        run: |
          sed -i "s/^Version: .*/Version: ${VERSION}/" debian/DEBIAN/control
          cat debian/DEBIAN/control

      - name: Prepare Debian package structure
        run: |
          cp -rT .next/standalone debian/usr/share/dashboard
          cp -r .next/static debian/usr/share/dashboard/.next
          cp -r public debian/usr/share/dashboard

      - name: Build Debian package
        run: dpkg-deb --build debian relayer-admin-dashboard.deb

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build relayer image
        id: build-and-push-relayer
        uses: docker/build-push-action@v6
        with:
          context: https://github.com/icon-project/relayer-docker.git#:admin-dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            - DASHBOARD_VERSION=${{ github.ref_name }}
          tags: |
            iconcommunity/relayer-admin-dashboard:latest
            iconcommunity/relayer-admin-dashboard:${{ github.ref_name }}

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign artifacts
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_YES: true
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY iconcommunity/relayer-admin-dashboard:latest
          cosign sign --key env://COSIGN_PRIVATE_KEY iconcommunity/relayer-admin-dashboard:${{ github.ref_name }}
          cosign sign-blob --key env://COSIGN_PRIVATE_KEY relayer-admin-dashboard.deb
          cosign public-key --key env://COSIGN_PRIVATE_KEY > cosign.pub

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            relayer-admin-dashboard.deb
            relayer-admin-dashboard.deb.sig
            cosign.pub
          tag_name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
          draft: false
          make_latest: ${{ github.ref_name == 'v*.*.*' && inputs.is_stable == 'true' }}
          prerelease: ${{ github.ref_name == 'v*.*.*-*' }}
