name: Release Debian package

on:
  push:
    tags:
      - "v*.*.*" # run on semver tags
      - "v*.*.*-*" # run on pre-release tags
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build Next.js application
        run: bun run build

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update control file version
        run: |
          sed -i "s/^Version: .*/Version: ${VERSION}/" debian/DEBIAN/control
          cat debian/DEBIAN/control

      - name: Prepare Debian package structure
        run: |
          cp -r .next/standalone/* debian/usr/share/dashboard
          cp -r .next/static debian/usr/share/dashboard/.next
          cp -r public debian/usr/share/dashboard

      - name: Build Debian package
        run: dpkg-deb --build debian relayer-admin-dashboard.deb

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: relayer-admin-dashboard-debian
          path: relayer-admin-dashboard.deb

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: relayer-admin-dashboard.deb
          generate_release_notes: true
          make_latest: true
          prerelease: ${{ contains(github.ref, '-') }}
